### ISSUE TITLE
UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'name' of undefined

### ISSUE THREAD

**Issue by rastogi-rishabh** [mdix/i18n-auto-translate#1]
UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'name' of undefined
at mapOverridesOnMasterLanguageContent (/home/myName/myProject/node_modules/i18n-auto-translate/src/overrides.js:56:58)

Getting this error when trying to run it.

**Comment by mdix** [comment]
I'm looking into it. Thanks for reporting and sorry for any inconvenience.

**Comment by mdix** [comment]
Mind posting your `i18n-auto-translate.config.js` file? Did you define a master language there?

**Comment by rastogi-rishabh** [comment]
Yes, I did define a master language.
